version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: es8
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 10s
      retries: 5

  siem:
    build:
      context: ./
    container_name: siem_light
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "514:514/udp"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
